{
 "title": "Go | PHP-FPM (3901)",
 "description": "PHP-FPM monitoring dashboard",
 "tags": [
  "GoEPFL",
  "go.epfl.ch",
  "php-fpm",
  "provisionned"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {
     "query": "label_values(phpfpm_accepted_connections_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Accepted Connections",
   "type": "graph",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_accepted_connections_total{instance=~\"^$Host$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Max Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_active_max_processes{instance=~\"^$Host$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_listen_queue_connections{instance=~\"^$Host$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listen Queue Length Connections",
   "type": "graph",
   "description": "The length of the socket queue, dictating maximum number of pending connections",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_listen_queue_length_connections{instance=~\"^$Host$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listen Queue Max Connections",
   "type": "graph",
   "description": "Max number of connections the listen queue has reached since FPM start",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue_max_connections{instance=~\"^$Host$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Children Reached",
   "type": "graph",
   "description": "Number of times the process limit has been reached",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached_total{instance=~\"^$Host$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_processes_total{instance=~\"^$Host$\"}) by (instance, state)",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_slow_requests_total{instance=~\"^$Host$\"}) by (instance)",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  }
 ]
}