---
# ------------------------------------------------- Directories and static files
- name: Create various destination directories for noc files
  file:
    path: "{{ data_path }}/grafana/{{ item }}"
    state: directory
  with_items:
    - conf

- name: Create writable directories to be used as mount points
  file:
    path: "{{ data_path }}/grafana/{{ item }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - logs
    - data
    - data/plugins

- name: Copy Grafana provisionned dashboards
  copy:
    src: "provisioning/dashboards/{{ item }}"
    dest: "{{ data_path }}/grafana/provisioning/dashboards/"
  with_items:
    - dashboards.yml
    - GitLab/
    - Go/
    - GoTest/
    - NOC/
    - PhDAssess/
    - WordPress/
  register: grafana_static_files

# -------------------------------------------------------------------- Templates
- name: Copy Grafana template config
  template:
    src: "grafana/{{ item }}"
    dest: "{{ data_path }}/grafana/{{ item }}"
  with_items:
    - conf/grafana.ini
    - provisioning/datasources/idevfsd-prometheus.yml
    - provisioning/datasources/go-prom-ds.yml
    - provisioning/datasources/go-test-prom-ds.yml
    - provisioning/notifiers/telegram.yml
  register: grafana_config_files

# -------------------------------------------------------------------- Container
- name: "Pull Grafana {{ grafana_image_qualified }}"
  community.docker.docker_image:
    name: "{{ grafana_image_qualified }}"
    source: pull

- name: Run Grafana
  docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image_qualified }}"
    detach: yes
    restart_policy: unless-stopped
    recreate: >-
      {{ grafana_config_files is defined and grafana_config_files is changed or grafana_static_files is defined and grafana_static_files is changed }}
    network_mode: "{{ backend_network_name }}"
    volumes:
      - "{{ data_path }}/grafana/data:/var/lib/grafana"
      - "{{ data_path }}/grafana/conf/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ data_path }}/grafana/provisioning:/etc/grafana/provisioning"
    env:
      GF_INSTALL_PLUGINS: "{{ grafana.plugins | join(',') }}"
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "3"
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: "Host(`grafana{{ dns_suffix }}.{{ frontend.domain }}`, `grafana.noc{{ dns_suffix }}.{{ frontend.alt_domain }}`)"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.tls.certresolver: "letsencrypt"
      traefik.docker.network: "{{ backend_network_name }}"
