---
version: 1
dependencies:
  galaxy: requirements.yml
  system: bindep.txt
  # wheel deps should be used only for packages that are not available as rpms
  python: requirements.txt
additional_build_steps:
  append:
    - >-
      RUN set -ex &&
      /output/install-from-bindep && rm -rf /output/wheels &&
      alternatives --set python /usr/bin/python3 &&
      dnf -y upgrade &&
      dnf autoremove
    - |-
      # add some helpful CLI commands to check we do not remove them inadvertently and output some helpful version information at build time.
      RUN set -ex \
        && molecule --version \
        && molecule drivers \
        && ansible-lint --version \
        && podman --version \
        && python --version \
        && git --version
