- name: Check if environment is set
  hosts: all
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

# - name: Networking configuration (DHCP / DNS)
#   hosts: all
#   gather_facts: yes
#   roles:
#     - role: roles/networking
#       tags: networking
#       apply:
#         tags: networking

- name: ssh access
  hosts: all
  gather_facts: no
  roles:
    - role: roles/access
      tags:
        - ssh
        - access
      apply:
        tags:
          - ssh
          - access

- name: Networking configuration (DHCP / DNS)
  hosts: all
  gather_facts: yes
  roles:
    - role: roles/networking
      tags: networking
      apply:
        tags: networking

- name: Postfix mail black hole
  hosts: noc_dev
  gather_facts: no
  roles:
    - name: postfix
      role: roles/postfix
      tags: postfix

- name: External NOC
  hosts: noc
  gather_facts: no
  roles:
    - name: docker
      role: nickjj.docker
      become: yes
      become_user: root
      tags: docker

    - name: noc
      role: roles/noc
      tags: noc

    - name: traefik
      role: roles/traefik
      tags: traefik

    - name: alertmanager
      role: roles/alertmanager
      tags:
        - noc
        - alertmanager

    - name: alert_tg_bot
      role: roles/alert_tg_bot
      tags:
        - noc
        - alert_tg_bot

    - name: blackbox_exporter
      role: roles/blackbox_exporter
      tags:
        - noc
        - bbe

    - name: grafana
      role: roles/grafana
      tags:
        - noc
        - grafana

    - name: node_exporter
      role: roles/node_exporter
      tags:
        - noc
        - nodeexporter

    - name: ssh exporter
      role: roles/ssh-exporter
      tags:
        - noc
        - ssh-exporter

    - name: prometheus
      role: roles/prometheus
      tags:
        - noc
        - prometheus
        - prometheus.force-restart

    - name: pushgateway
      role: roles/pushgateway
      tags:
        - noc
        - pushgateway

    - name: kuma
      role: roles/kuma
      tags:
        - noc
        - kuma

    - name: mgmt
      role: roles/mgmt
      tags: mgmt

- name: Postfix mail black hole
  hosts: noc_test
  gather_facts: no
  roles:
    - name: postfix
      role: roles/postfix
      tags: postfix
