{
 "title": "Mastodon@EPFL (Public)",
 "tags": [ "Mastodon" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src='https://raw.githubusercontent.com/epfl-si/mastodon.ops/8acd3a36898938dbf51442faa67d9816e5e6e5c8/media/Mastodon%40EPFL.svg' height='100%'>\n"
   }
  },
  {
   "title": "Users count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Local boosts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_boost_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local statuses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_status_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local favourites",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_favourite_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Boosts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_boost_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Statuses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_status_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Favourites",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_favourite_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mastodon@EPFL's users",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ruby_mastodon_user_count", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}