{
 "title": "Mastodon@EPFL",
 "tags": [ "Mastodon" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src='https://raw.githubusercontent.com/epfl-si/mastodon.ops/8acd3a36898938dbf51442faa67d9816e5e6e5c8/media/Mastodon%40EPFL.svg' height='100%'>\n"
   }
  },
  {
   "title": "Users count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Local statuses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_status_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local boosts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_boost_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local favourites",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_favourite_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_status_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Favourites",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_favourite_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Boosts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_boost_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mastodon@EPFL's users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "ruby_mastodon_user_count", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Disk monitoring",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"mastodon-prod\", mountpoint=~\"/|/srv/(.*)\"} * 100) / node_filesystem_size_bytes{instance=\"mastodon-prod\", mountpoint=~\"/|/srv/(.*)\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Traefik monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total) by (protocol)",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum) / sum(traefik_service_requests_total) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Requests in last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m]))",
     "legendFormat": "{{requests}}"
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol=~\"http|https\",code=\"200\"}[5m])) by (backend,method)",
     "legendFormat": "{{service}} {{method}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol=~\"http|https\",code!=\"200\"}[5m])) by (backend,method,code)",
     "legendFormat": "{{backend}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"traefik\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_http_requests_total{controller=\"api/v1/statuses\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruby_http_requests_total{controller=\"api/v1/statuses\", status!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}