{
 "title": "Ressenti",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Site",
    "query": "label_values(vpsi_wwp_federation:probe_duration_seconds,instance)"
   },
   {
    "name": "origin",
    "label": "Origin",
    "query": "label_values(vpsi_wwp_federation:probe_duration_seconds,origin)"
   }
  ]
 },
 "panels": [
  {
   "title": "Blackbox / http code",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{probe=\"blackbox\", instance=~\"$instance\", origin=~\"$origin\"}",
     "legendFormat": "{{origin}} <- {{instance}}"
    }
   ]
  },
  {
   "title": "Ressenti (full page ready)",
   "type": "graph",
   "description": "Time to full page generation",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{probe=\"ressenti_firefox\", instance=~\"$instance\", origin=~\"$origin\"}",
     "legendFormat": " {{origin}} <- {{instance}}"
    }
   ]
  },
  {
   "title": "Blackbox / probe (sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{probe=\"blackbox\", instance=~\"$instance\", origin=~\"$origin\"}",
     "legendFormat": "{{origin}} <- dns {{instance}}"
    },
    {
     "expr": "probe_duration_seconds{probe=\"blackbox\", instance=~\"$instance\", origin=~\"$origin\"}",
     "legendFormat": "{{origin}} <- total {{instance}}"
    },
    {
     "expr": "probe_http_duration_seconds{probe=\"blackbox\", instance=~\"$instance\", origin=~\"$origin\"}",
     "legendFormat": "{{origin}} <- {{phase}} {{instance}}"
    }
   ]
  },
  {
   "title": "Blackbox / ssl cert expire",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "1000 * probe_ssl_earliest_cert_expiry{probe=\"blackbox\", instance=~\"$instance\", origin=~\"$origin\"}",
     "legendFormat": "{{origin}} <- {{instance}}"
    }
   ]
  }
 ]
}