all:
  vars:
    runenv: prod
    dns_suffix: ""

noc:
  children:
    noc_prod

noc_prod:
  hosts:
    noc_prod1:
      ansible_host: 86.119.37.70
      ansible_port: 22
      ansible_user: root
      noc_install_path: /srv/noc
