all:
  vars:
    runenv: dev
    dnspostfix: "-tst"

noc:
  children:
    noc_dev

noc_dev:
  hosts:
    noc_test1:
      ansible_host: noc-tst.idev-fsd.ml
      ansible_port: 22
      ansible_user: root
      noc_install_path: /srv/noc
