{
 "title": "WP Detail",
 "tags": [
  "wordpress",
  "provisionned"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "wp_site", "label": "Site", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "General details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Screenshot",
   "type": "text",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://image.thum.io/get/$wp_site\" title=\"screenshot of $wp_site\" style=\"width: 100%; height: auto;\"/>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"$wp_site\"}"
    }
   ]
  },
  {
   "title": "Last backup have been done since",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - restic_success{url=\"$wp_site\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=\"wordpresses@epfl\",origin=\"noc-zurich\",instance=\"$wp_site\"}*1000"
    }
   ]
  },
  {
   "title": "Site languages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(epfl_wp_site_langs{url=\"$wp_site\"})by(lang)"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"wordpresses@epfl\",origin=\"noc-zurich\", instance=\"$wp_site\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Last backup date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "restic_success{url=\"$wp_site\"} * 1000"
    }
   ]
  },
  {
   "title": "Duration of last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "restic_success{url=\"$wp_site\"} - restic_start{url=\"$wp_site\"}"
    }
   ]
  },
  {
   "title": "Probe redirection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_redirects{instance=\"$wp_site\",job=\"wordpresses@epfl\",origin=\"noc-zurich\",probe=\"blackbox\"}"
    }
   ]
  },
  {
   "title": "Total size of $wp_site backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "restic_files_total_size{url=\"$wp_site\"}"
    }
   ]
  },
  {
   "title": "HTTP version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_version{job=\"wordpresses@epfl\",origin=\"noc-zurich\", instance=\"$wp_site\"}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"wordpresses@epfl\",origin=\"noc-zurich\", instance=~\"$wp_site\"}",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  { "title": "Backup stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Backup total size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "restic_files_total_size{url=\"$wp_site\"}",
     "legendFormat": "restic"
    },
    {
     "expr": "s3_backup_files_total_size{url=\"$wp_site\"}",
     "legendFormat": "aws"
    }
   ]
  },
  {
   "title": "Files total count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "restic_files_total_file_count{url=\"$wp_site\"}",
     "legendFormat": "restic"
    },
    {
     "expr": "s3_backup_files_total_file_count{url=\"$wp_site\"}",
     "legendFormat": "aws"
    }
   ]
  },
  {
   "title": "SQL  size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "restic_sql_total_size{url=\"$wp_site\"}",
     "legendFormat": "restic"
    },
    {
     "expr": "s3_backup_sql_total_size{url=\"$wp_site\"}",
     "legendFormat": "aws"
    }
   ]
  },
  {
   "title": "SQL total count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "s3_backup_files_total_file_count{url=\"$wp_site\"}",
     "legendFormat": "restic"
    },
    {
     "expr": "s3_backup_sql_total_file_count{url=\"$wp_site\"}",
     "legendFormat": "aws"
    }
   ]
  },
  { "title": "wp_disk_usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Disk usage total size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wp_disk_usage_size_total{url=~\"$wp_site\",job=\"wp_disk_usage\"}"
    }
   ]
  },
  {
   "title": "Disk usage total files count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wp_disk_usage_files_total{url=~\"$wp_site\",job=\"wp_disk_usage\"}"
    }
   ]
  },
  { "title": "Prob info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Avg probe duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=\"wordpresses@epfl\",origin=\"noc-zurich\", instance=\"$wp_site\"})"
    }
   ]
  },
  {
   "title": "Avg DNS lookup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=\"$wp_site\"})"
    }
   ]
  },
  {
   "title": "probe http duration seconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"wordpresses@epfl\",origin=\"noc-zurich\", instance=\"$wp_site\"}",
     "legendFormat": "total"
    },
    {
     "expr": "probe_http_duration_seconds{job=\"wordpresses@epfl\",origin=\"noc-zurich\", instance=\"$wp_site\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}