{
 "title": "WP Backup",
 "tags": [
  "wordpress",
  "provisionned"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "wp_site",
    "label": "Site",
    "query": "label_values(restic_files_total_file_count{job=\"backup\"},url)"
   }
  ]
 },
 "panels": [
  { "title": "Sum all wordpresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(s3_backup_files_total_size) + sum(s3_backup_sql_total_size) ",
     "legendFormat": "s3_backup"
    },
    {
     "expr": "sum(restic_files_total_size) + sum(restic_sql_total_size) ",
     "legendFormat": "restic"
    },
    { "expr": "sum(wp_disk_usage_size_total)", "legendFormat": "wp_disk_usage" }
   ]
  },
  { "title": "File", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "File total count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "restic_files_total_file_count{url=~\"$wp_site\"}"
    },
    {
     "expr": "s3_backup_files_total_file_count{url=~\"$wp_site\"}"
    },
    {
     "expr": "wp_disk_usage_files_total{url=~\"$wp_site\"}"
    }
   ]
  },
  {
   "title": "Files total size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "restic_files_total_size{url=~\"$wp_site\"}"
    },
    {
     "expr": "s3_backup_files_total_size{url=~\"$wp_site\"}"
    },
    {
     "expr": "wp_disk_usage_size_total{url=~\"$wp_site\"}"
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "SQL total count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "restic_sql_total_file_count{url=~\"$wp_site\"}"
    },
    {
     "expr": "s3_backup_sql_total_file_count{url=~\"$wp_site\"}"
    }
   ]
  },
  {
   "title": "SQL total size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "restic_sql_total_size{url=~\"$wp_site\"}"
    },
    {
     "expr": "s3_backup_sql_total_size{url=~\"$wp_site\"}"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk usage files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wp_disk_usage_files_uploads{url=~\"$wp_site\"}"
    },
    {
     "expr": "wp_disk_usage_files_wp_content{url=~\"$wp_site\"}"
    },
    {}
   ]
  },
  {
   "title": "Disk usage size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wp_disk_usage_size_uploads{url=~\"$wp_site\"}"
    },
    {
     "expr": "wp_disk_usage_size_wp_content{url=~\"$wp_site\"}"
    },
    {}
   ]
  }
 ]
}