{
 "title": "WordPress general",
 "description": "Main dashboard for WordPresses",
 "tags": [
  "wordpress",
  "provisionned"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "wp_site", "label": "Sites", "query": "label_values(url)" },
   { "name": "wp_env", "label": "Openshift env", "query": "label_values(wp_env)" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Status overview ($wp_env)",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"wordpresses@epfl\",origin=\"noc-zurich\",wp_env=~\"$wp_env\"}",
     "legendFormat": "  {{ instance }}"
    }
   ]
  },
  {
   "title": "SSL Expiry ($wp_env)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(probe_ssl_earliest_cert_expiry{wp_env=~\"$wp_env\",job=\"wordpresses@epfl\",origin=\"noc-zurich\"}-time()) by (instance)"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Site http_code != 200",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vprobe_http_status_code != 200" },
    {}
   ]
  },
  {
   "title": "Sites != 200",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"wordpresses@epfl\",origin=\"noc-zurich\",wp_env=~\"$wp_env\"} != 200",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Languages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Lang repartition ($wp_env / $wp_site)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs{wp_env=~'$wp_env',url=~'$wp_site'})by(lang))",
     "legendFormat": "Lang: '{{ lang }}'"
    }
   ]
  },
  {
   "title": "Langues repartition ($wp_env)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs{wp_env=~'$wp_env'})by(lang))",
     "legendFormat": "{{ lang }}"
    }
   ]
  },
  {
   "title": "Sites with more that 2 langs ($wp_env)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Langs" } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs{wp_env=~'$wp_env'}) by (url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Langues by wp_env",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs)by(wp_env,lang))",
     "legendFormat": "{{wp_env}}/{{ lang }}"
    }
   ]
  },
  { "title": "Pages & Posts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total pages ($wp_env / $wp_site)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(epfl_wp_site_pages{wp_env=~'$wp_env',url=~'$wp_site'})"
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Total files count backups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "restic_s3_total_file_count", "legendFormat": "{{ url }} ({{ wp_env }})" },
    {
     "expr": "sum(restic_s3_total_file_count)",
     "legendFormat": "total sum"
    }
   ]
  },
  {
   "title": "Total size backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(restic_s3_total_size)" }
   ]
  },
  {
   "title": "Restic backup duration ($wp_env / $wp_site)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(restic_success{url=~\"$wp_site\",wp_env=~\"$wp_env\"}) by (url) - sum(restic_start{url=~\"$wp_site\",wp_env=~\"$wp_env\"}) by (url)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  { "title": "Menus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Menu count ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_menu_count{wp_env=~'$wp_env',url=~'$wp_site'})by(url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu unique count ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_menu_unique_count{wp_env=~'$wp_env',url=~'$wp_site'})by(url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu sync failing ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "sort_desc(epfl_externalmenu_sync_failing_since{wp_env=~'$wp_env',url=~'$wp_site'}*1000)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu last sync success ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "sort_desc(epfl_externalmenu_sync_last_success{wp_env=~'$wp_env',url=~'$wp_site'}*1000)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu orphan ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "menu" } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_menu_orphan_count{wp_env=~'$wp_env',url=~'$wp_site'})by(url))",
     "legendFormat": "{{ url }}"
    }
   ]
  }
 ]
}