{
 "title": "WP Plugins and Blocks",
 "tags": [
  "wordpress",
  "provisionned"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Plugin count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_plugin_count{url=\"https://www.epfl.ch/campus/services/canari/\"}"
    }
   ]
  },
  {
   "title": "Block count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_block_count{url=\"https://www.epfl.ch/campus/services/canari/\"}"
    }
   ]
  },
  {
   "title": "Plugin Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_plugin_name{url=\"https://www.epfl.ch/campus/services/canari/\"}",
     "legendFormat": "{{ pluginName }}"
    }
   ]
  },
  {
   "title": "Block usage count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_block_usage_count{url=\"https://www.epfl.ch/campus/services/canari/\"}",
     "legendFormat": "{{ blockName }}"
    }
   ]
  }
 ]
}