#!/usr/bin/env ruby

require 'net/http'
require 'json'

url = 'https://wp-veritas.epfl.ch/api/v1/sites'
uri = URI(url)
response = Net::HTTP.get(uri)

src = JSON.parse(response).select{|u| u['userExperience']}
lst = src.map do |u|
  uu = URI(u['url'])
  ll = u.key?('userExperienceUniqueLabel') ? u['userExperienceUniqueLabel'] : ''
  if ll.empty?
    ll =  if uu.path.empty?
            uu.host
          else
            uu.host + uu.path.split("/")[0..2].join("_")
          end
  end
  { url: uu.to_s, slug: ll }
end

print JSON.pretty_generate(lst) 
