{
 "title": "Gitlab Statistics",
 "description": "Stats from https://github.com/epfl-dojo/GitlabStatisticsPrometheusExporter",
 "tags": [
  "gitlab",
  "statistics",
  "provisionned"
 ],
 "time": { "from": "now-7d", "to": "now-1m" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>GitLab EPFL statistics</h1></center>"
   }
  },
  {
   "title": "General info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_users_total", "legendFormat": "Gitlab Total Users" }
   ]
  },
  {
   "title": "Groups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_groups_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_projects_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "issues" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "gitlab_issues_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Forks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_forks_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "PRs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_merge_requests_total", "legendFormat": "Gitlab Total PRs" }
   ]
  },
  {
   "title": "SSH Keys",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_ssh_keys_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Notes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_notes_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Snippets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_snippets_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Milestones",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_milestones_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gitlab_active_users_total", "legendFormat": "Gitlab Total Projects" }
   ]
  },
  {
   "title": "Users info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Users Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_users_total", "legendFormat": "users" }
   ]
  },
  {
   "title": "Last month new users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_active_users_total[4w]))",
     "legendFormat": "Last week new users"
    }
   ]
  },
  {
   "title": "Last week new users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_active_users_total[1w]))",
     "legendFormat": "Last week new users"
    }
   ]
  },
  {
   "title": "Last day new users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_active_users_total[1d]))",
     "legendFormat": "Last day new users"
    }
   ]
  },
  {
   "title": "Groups info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Groups Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_groups_total", "legendFormat": "groups" }
   ]
  },
  {
   "title": "Last month new groups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_groups_total[4w]))",
     "legendFormat": "Last month new groups"
    }
   ]
  },
  {
   "title": "Last week new groups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_groups_total[1w]))",
     "legendFormat": "Last week new groupes"
    }
   ]
  },
  {
   "title": "Last day new groups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_groups_total[1d]))",
     "legendFormat": "Last day new groups"
    }
   ]
  },
  {
   "title": "Projects info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Projects Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_projects_total", "legendFormat": "projects" }
   ]
  },
  {
   "title": "Last month new projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_projects_total[4w]))",
     "legendFormat": "Last month new projects"
    }
   ]
  },
  {
   "title": "Last week new projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_projects_total[1w]))",
     "legendFormat": "Last week new projects"
    }
   ]
  },
  {
   "title": "Last day new projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_projects_total[1d]))",
     "legendFormat": "Last day new projects"
    }
   ]
  },
  {
   "title": "Issues, forks and PRs info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Issues Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_issues_total", "legendFormat": "issues" }
   ]
  },
  {
   "title": "Forks Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_forks_total", "legendFormat": "forks" }
   ]
  },
  {
   "title": "PRs Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_merge_requests_total", "legendFormat": "PRs" }
   ]
  },
  {
   "title": "Last month new issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_issues_total[4w]))",
     "legendFormat": "Last month new issues"
    }
   ]
  },
  {
   "title": "Last week new issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_issues_total[1w]))",
     "legendFormat": "Last week new issues"
    }
   ]
  },
  {
   "title": "Last month new forks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_forks_total[4w]))",
     "legendFormat": "Last month new issues"
    }
   ]
  },
  {
   "title": "Last week new forks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_forks_total[1w]))",
     "legendFormat": "Last week new forks"
    }
   ]
  },
  {
   "title": "Last month new PRs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_merge_requests_total[4w]))",
     "legendFormat": "Last month new PRs"
    }
   ]
  },
  {
   "title": "Last week new PRs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(delta(gitlab_merge_requests_total[1w]))",
     "legendFormat": "Last week new PRs"
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Groups per users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab_groups_total/gitlab_users_total)",
     "legendFormat": "gitlab_active_users_total / gitlab_groups_total"
    }
   ]
  },
  {
   "title": "Issues per users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab_issues_total/gitlab_users_total)",
     "legendFormat": "gitlab_users_total/gitlab_issues_total"
    }
   ]
  },
  {
   "title": "SSH Keys per users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab_ssh_keys_total/gitlab_users_total)",
     "legendFormat": "gitlab_ssh_keys_total/gitlab_users_total"
    }
   ]
  }
 ]
}