{
 "title": "GitLab EPFL",
 "tags": [
  "gitlab",
  "provisionned"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{service=\"gitlab\"},instance)"
   },
   {
    "name": "network_interface",
    "label": "Network Interface",
    "query": "node_network_iface_id{environment=\"prod\",instance=\"$instance\"}"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitlab_user_count" }
   ]
  },
  {
   "title": "Groups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitlab_group_count" }
   ]
  },
  {
   "title": "Projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitlab_project_count" },
    {}
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "gitlab_issue_count" },
    {}
   ]
  },
  {
   "title": "gitlab.epfl.ch % disc used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100-(100*instance:node_filesystem_avail:ratio{device=\"rootfs\",environment=\"prod\",fstype=\"rootfs\",instance=\"$instance\",job=\"node\",mountpoint=\"/\",service=\"gitlab\"})",
     "legendFormat": "% used"
    }
   ]
  },
  {
   "title": "gitlab.epfl.ch % NAS used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100-(100*instance:node_filesystem_avail:ratio{device=\"nas-app-ma-nfs1:/si_gitlab_app/backup\",environment=\"prod\",fstype=\"nfs\",instance=\"$instance\",job=\"node\",mountpoint=\"/var/opt/gitlab/backups\",service=\"gitlab\"})",
     "legendFormat": "% NAS used"
    }
   ]
  },
  {
   "title": "Probe HTTP duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{slug=\"go\",origin=\"zurich\",phase=\"connect\"}",
     "legendFormat": "connect"
    },
    {
     "expr": "probe_http_duration_seconds{slug=\"go\",origin=\"zurich\",phase=\"resolve\"}",
     "legendFormat": "resolve"
    },
    {
     "expr": "probe_http_duration_seconds{slug=\"go\",origin=\"zurich\",phase=\"tls\"}",
     "legendFormat": "tls"
    },
    {
     "expr": "probe_http_duration_seconds{slug=\"go\",origin=\"zurich\",phase=\"transfer\"}",
     "legendFormat": "transfer"
    },
    {
     "expr": "probe_http_duration_seconds{slug=\"go\",origin=\"zurich\",phase=\"processing\"}",
     "legendFormat": "processing"
    },
    {
     "expr": "sum(avg_over_time(probe_http_duration_seconds{slug=\"go\",origin=\"zurich\"}[5m]))",
     "legendFormat": "avg_over_time"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Users count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_user_count" }
   ]
  },
  {
   "title": "Projects count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "gitlab_project_count" }
   ]
  },
  {
   "title": "gitlab auth total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_auth_user_authenticated_total"
    },
    {
     "expr": "gitlab_auth_user_unauthenticated_total"
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{environment=\"prod\",instance=~\"$instance\",device=~\"$network_interface\"}[15m]))",
     "legendFormat": "TX sum $network_interface"
    },
    {
     "expr": "-1*sum(rate(node_network_receive_bytes_total{environment=\"prod\",instance=~\"$instance\",device=~\"$network_interface\"}[15m]))",
     "legendFormat": "RX sum $network_interface"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{environment=\"prod\",instance=~\"$instance\",device=~\"$network_interface\"}[1m])",
     "legendFormat": "TX rate  $network_interface"
    },
    {
     "expr": "-1*rate(node_network_receive_bytes_total{environment=\"prod\",instance=~\"$instance\",device=~\"$network_interface\"}[1m])",
     "legendFormat": "RX rate  $network_interface"
    }
   ]
  },
  { "title": "Discs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100-(100*instance:node_filesystem_avail:ratio{device=\"rootfs\",environment=\"prod\",fstype=\"rootfs\",instance=\"$instance\",job=\"node\",mountpoint=\"/\",service=\"gitlab\"})",
     "legendFormat": "% disc usage"
    }
   ]
  }
 ]
}