# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: go-test-prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: go-test-prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: go_test_prom
    # <string> url
    url: {{ _noc_secrets.grafana.datasources.gotest.url }}
    # <string> Deprecated, use secureJsonData.password
    password:
    # <string> database user, if used
    user:
    # <string> database name, if used
    database:
    # <bool> enable/disable basic auth
    basicAuth: true
    # <string> basic auth username
    basicAuthUser: {{ _noc_secrets.grafana.datasources.gotest.username }}
    # <string> Deprecated, use secureJsonData.basicAuthPassword
    basicAuthPassword:
    # <bool> enable/disable with credentials headers
    withCredentials:
    # <bool> mark as default datasource. Max one per org
    isDefault: false
    # <map> fields that will be converted to json and stored in jsonData
    # jsonData:
    #   graphiteVersion: '1.1'
    #   tlsAuth: true
    #   tlsAuthWithCACert: true
    # <string> json object of data that will be encrypted.
    secureJsonData:
      tlsCACert:
      tlsClientCert:
      tlsClientKey:
      # <string> database password, if used
      password:
      # <string> basic auth password
      basicAuthPassword:  {{ _noc_secrets.grafana.datasources.gotest.password }}
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false
