- name: Check if environment is set
  hosts: all
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

- name: Postfix mail black hole
  hosts: noc_dev
  gather_facts: no   # Not yet
  roles:
    - name: postfix
      role: ../roles/postfix
      tags: postfix

- name: External NOC
  hosts: noc
  gather_facts: no   # Not yet
  # Variables common to all roles
  roles:
    - name: docker
      role: nickjj.docker
      become: yes
      become_user: root
      tags: docker

    - name: noc
      role: ../roles/noc
      tags: noc

    - name: traefik
      role: ../roles/traefik
      tags: traefik

    - name: alertmanager
      role: ../roles/alertmanager
      tags:
        - noc
        - alertmanager

    - name: alert_tg_bot
      role: ../roles/alert_tg_bot
      tags:
        - noc
        - alert_tg_bot

    - name: blackbox_exporter
      role: ../roles/blackbox_exporter
      tags:
        - noc
        - bbe

    - name: grafana
      role: ../roles/grafana
      tags:
        - noc
        - grafana

    - name: node_exporter
      role: ../roles/node_exporter
      tags:
        - noc
        - nodeexporter

    - name: prometheus
      role: ../roles/prometheus
      tags:
        - noc
        - prometheus
        - prometheus.force-restart

    - name: pushgateway
      role: ../roles/pushgateway
      tags:
        - noc
        - pushgateway

    - name: mgmt
      role: ../roles/mgmt
      tags: mgmt
