{
 "title": "ZeebeDB dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zeebe_db_column_family_entries{column_family=\"JOBS\"}",
     "legendFormat": "{{column_family}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(zeebe_db_column_family_incident_entries)",
     "legendFormat": "INCIDENT"
    }
   ]
  },
  {
   "title": "Errored",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "zeebe_db_column_family_incident_entries",
     "legendFormat": "{{error_message}}"
    }
   ]
  },
  {
   "title": "Column families",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "zeebe_db_column_family_entries", "legendFormat": "{{column_family}}" }
   ]
  },
  {
   "title": "DB scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(zeebe_db_read_duration_seconds_sum[5m]) / rate(zeebe_db_read_duration_seconds_count[5m])"
    }
   ]
  }
 ]
}