{
 "title": "WP Menu API",
 "description": "Monitoring for the menus' API",
 "tags": [
  "menu_api",
  "WordPress"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Menu API Errors count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(menu_api_errors_count[5m])) by (message)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Menu API Errors count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(menu_api_errors_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(menu_api_http_requests_count[10m])) by (statusCode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Menu API Orphan pages count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(menu_api_orphan_pages_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Menu Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(menu_api_pages_total) by (lang)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Menu API External Detached Menus",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(menu_api_external_detached_menus_total)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average refresh duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "menu_api_refresh_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average call duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(menu_api_wp_api_call_duration_seconds)/count(menu_api_wp_api_call_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}