---
# vars for prometheus
prometheus_port: 9090
prometheus_container_name: "prometheus"
prometheus_image: "prom/prometheus"
prometheus_version: "v2.20.1"

prometheus_debug: '{{ dnspostfix == "-tst" }}'

urls:
  fsd:
    - name: gitlab
      slug: gitlab
      url: https://gitlab.epfl.ch
    - name: go
      slug: go
      url: https://go.epfl.ch
    - name: igm
      slug: igm
      url: https://sti.epfl.ch/research/institutes/igm
    - name: support-epfl
      slug: support-epfl
      url: https://support.epfl.ch/epfl
    - name: sti
      slug: sti
      url: https://sti.epfl.ch
  c2c:
    - name: actu
      slug: actu
      url: https://actu.epfl.ch
    - name: memento
      slug: memento
      url: https://memento.epfl.ch
    - name: people
      slug: people
      url: https://people.epfl.ch
    - name: epfl-about
      slug: www_epfl_ch_about
      url: https://www.epfl.ch/about/fr/a-propos
    - name: education
      slug: www_epfl_ch_education
      url: https://www.epfl.ch/education
    - name: research
      slug: www_epfl_ch_research
      url: https://www.epfl.ch/research
    - name: innovation
      slug: www_epfl_ch_innovation
      url: https://www.epfl.ch/innovation
    - name: schools
      slug: www_epfl_ch_schools
      url: https://www.epfl.ch/schools
    - name: campus
      slug: www_epfl_ch_campus
      url: https://www.epfl.ch/campus
    - name: services
      slug: www_epfl_ch_campus_services
      url: https://www.epfl.ch/campus/services
    - name: labs
      slug: www.epfl.ch_labs
      url: https://www.epfl.ch/labs


  veritas: "{{ sites_from_veritas.stdout | default('[]') | from_json }}"

c2c:
  prefix: vpsi_wwp_federation
  metrics:
    - probe_dns_lookup_time_seconds
    - probe_duration_seconds
    - probe_http_content_length
    - probe_http_duration_seconds
    - probe_http_last_modified_timestamp_seconds
    - probe_http_status_code
    - probe_http_redirects
    - probe_failed_due_to_regex
    - probe_http_ssl
    - probe_http_version
    - probe_ip_protocol
    - probe_ssl_earliest_cert_expiry
    - probe_success

auth:
  legacy:
    username: "{{ _noc_secrets.prometheus.auth.legacy.username }}"
    password: "{{ _noc_secrets.prometheus.auth.legacy.password }}"
  gitlab:
    username: "{{ _noc_secrets.prometheus.auth.gitlab.username }}"
    password: "{{ _noc_secrets.prometheus.auth.gitlab.password }}"

sources:
  blackbox:
    - name: bbe-ch-zh
      origin: zurich
      server: "{{ blackboxexporter_container_name }}:{{ bbe.port | default('9115')}}"
      auth: '{{ auth.legacy }}'
    - name: bbe-fr-par
      origin: paris
      server: "bbe-paris.idev-fsd.ml:80"
      auth: '{{ auth.legacy }}'
  ressenti:
    - name: res-ch-zh
      module: firefox
      origin: zurich
      server: prob.86.119.40.68.nip.io
      auth: '{{ auth.legacy }}'
    - name: res-fr-par
      module: firefox
      origin: paris
      server: ressenti-paris.idev-fsd.ml
      auth: '{{ auth.legacy }}'
    # - name: res-fr-par2
    #   module: firefox
    #   origin: paris2
    #   server: ressenti-paris2.idev-fsd.ml
    #   auth: '{{ auth.legacy }}'
