#!/usr/bin/env ruby
require 'net/http'
require 'json'

url = 'https://wp-veritas.epfl.ch/api/v1/sites'
uri = URI(url)
response = Net::HTTP.get(uri)

src = JSON.parse(response)

lst = src.map do |u|
  is_monitored = u.key?('monitored') && u['monitored'] == true
  
  next unless is_monitored
  
  uu = URI(u['url'])
  
  ll = if uu.path.empty?
         uu.host
       else
         uu.host + uu.path.split("/")[0..2].join("_")
       end
  
  { url: uu.to_s, slug: ll, monitored: is_monitored }
end.compact

print JSON.pretty_generate(lst)
