{
 "title": "WordPress Main",
 "description": "Main dashboard for WordPresses",
 "tags": [
  "WordPress",
  "General",
  "provisionned"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "wp_site",
    "label": "Sites",
    "query": {
     "query": "label_values(up{job=\"wordpresses@epfl\",origin=\"noc-zurich\",probe=\"blackbox\",wp_env=~\"$wp_env\"},instance)"
    }
   },
   { "name": "wp_env", "label": "Openshift env", "query": { "query": "label_values(wp_env)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Status overview ($wp_env / $wp_site)",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"wordpresses@epfl\",origin=\"noc-zurich\",wp_env=~\"$wp_env\",instance=~\"$wp_site\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Backup overview ($wp_env / $wp_site)",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc((time() - restic_success{url=~\"$wp_site\",wp_env=~\"$wp_env\"})OR on() vector(31536000))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "HTTP status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"wordpresses@epfl\",origin=\"noc-zurich\",wp_env=~\"$wp_env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL Expiry ($wp_env)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(probe_ssl_earliest_cert_expiry{wp_env=~\"$wp_env\",job=\"wordpresses@epfl\",origin=\"noc-zurich\"}-time()) by (instance)"
    }
   ]
  },
  {
   "title": "HTTP Status ($wp_site / $wp_env)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"wordpresses@epfl\",origin=\"noc-zurich\",wp_env=~\"$wp_env\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lang repartition ($wp_env / $wp_site)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs{wp_env=~'$wp_env',url=~'$wp_site'})by(lang))",
     "legendFormat": "Lang: '{{ lang }}'"
    }
   ]
  },
  {
   "title": "Langues repartition ($wp_env)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs{wp_env=~'$wp_env'})by(lang))",
     "legendFormat": "{{ lang }}"
    }
   ]
  },
  {
   "title": "Sites with more that 2 langs ($wp_env)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Langs" } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs{wp_env=~'$wp_env'}) by (url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Langues by wp_env",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_langs)by(wp_env,lang))",
     "legendFormat": "{{wp_env}}/{{ lang }}"
    }
   ]
  },
  {
   "title": "Pages & Posts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total pages ($wp_env / $wp_site)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(epfl_wp_site_pages{wp_env=~\"$wp_env\",url=~\"$wp_site\"})"
    }
   ]
  },
  {
   "title": "Pages per site ($wp_env)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Pages" } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_wp_site_pages{wp_env=~'$wp_env'}) by (url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Restic start / success ($wp_site / $wp_env)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "restic_start{url=~\"$wp_site\", wp_env=~\"$wp_env\"}",
     "legendFormat": "{{ url }} ({{ wp_env }})"
    },
    {
     "expr": "restic_success{url=~\"$wp_site\", wp_env=~\"$wp_env\"}",
     "legendFormat": "{{ url }} ({{ wp_env }})"
    }
   ]
  },
  {
   "title": "Time since success backup ($wp_env)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(time() - restic_success{url=~\"$wp_site\",wp_env=~\"$wp_env\"})",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Restic backup duration ($wp_env / $wp_site)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort_desc(restic_success{url=~\"$wp_site\",wp_env=~\"$wp_env\"} - restic_start{url=~\"$wp_site\",wp_env=~\"$wp_env\"} > 0)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Last backup duration ($wp_env)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(sum(restic_success{url=~\"$wp_site\",wp_env=~\"$wp_env\"}) by (url) - sum(restic_start{url=~\"$wp_site\",wp_env=~\"$wp_env\"}) by (url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Total size backups ($wp_site/$wp_env)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(s3_backup_files_total_size{wp_env=~\"$wp_env\",url=~\"$wp_site\"}) + sum(s3_backup_sql_total_size{wp_env=~\"$wp_env\",url=~\"$wp_site\"}) "
    }
   ]
  },
  {
   "title": "Last backup size ($wp_env / $wp_site)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(restic_files_total_size{url=~\"$wp_site\",wp_env=~\"$wp_env\"})",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Menu count ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_menu_count{wp_env=~'$wp_env',url=~'$wp_site'})by(url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu unique count ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_menu_unique_count{wp_env=~'$wp_env',url=~'$wp_site'})by(url))",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu sync failing ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "sort_desc(epfl_externalmenu_sync_failing_since{wp_env=~'$wp_env',url=~'$wp_site'}*1000)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu last sync success ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "sort_desc(epfl_externalmenu_sync_last_success{wp_env=~'$wp_env',url=~'$wp_site'}*1000)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Menu orphan ($wp_env/$wp_site)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "menu" } },
   "targets": [
    {
     "expr": "sort_desc(sum(epfl_menu_orphan_count{wp_env=~'$wp_env',url=~'$wp_site'})by(url))",
     "legendFormat": "{{ url }}"
    }
   ]
  }
 ]
}