{
 "title": "WP Plugins and Blocks",
 "tags": [
  "WordPress",
  "Plugins",
  "provisionned"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "wp_site", "label": "Site", "query": "label_values(instance)" },
   { "name": "wp_plugin", "label": "Plugin", "query": "label_values(pluginName)" },
   { "name": "wp_block", "label": "Block", "query": "label_values(blockName)" }
  ]
 },
 "panels": [
  {
   "title": "Plugin count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_plugin_count{url=~\"$wp_site\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Plugin count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "epfl_wp_site_plugin_count", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Plugin Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_plugin_name{url=~\"$wp_site\"}",
     "legendFormat": "{{ pluginName }}"
    }
   ]
  },
  {
   "title": "By Plugin Name ($wp_plugin)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(epfl_wp_site_plugin_name{pluginName=~\"$wp_plugin\"}) by (pluginName)",
     "legendFormat": "{{ pluginName }}"
    }
   ]
  },
  {
   "title": "Block count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_block_count{url=~\"$wp_site\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block count by instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(epfl_wp_site_block_count) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block usage count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "epfl_wp_site_block_usage_count{url=~\"$wp_site\"}",
     "legendFormat": "{{ blockName }}"
    }
   ]
  },
  {
   "title": "Block usage count by blockName ($wp_block)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(epfl_wp_site_block_usage_count{blockName=~\"$wp_block\"}) by (blockName)",
     "legendFormat": "{{ blockName }}"
    }
   ]
  }
 ]
}