{% set letsencrypt_boilerplate = 'tls: { certResolver: letsencrypt }' %}

http:
  routers:
    traefik:
      rule: "Host(`traefik{{ dns_suffix }}.{{ frontend.domain }}`,`traefik.noc{{ dns_suffix }}.{{ frontend.alt_domain }}`)"
      service: "api@internal"
      entryPoints: ["websecure"]
      {{ letsencrypt_boilerplate }}

    metrics:
      rule: "Host(`traefik{{ dns_suffix }}.{{ frontend.domain }}`,`traefik.noc{{ dns_suffix }}.{{ frontend.alt_domain }}`) && PathPrefix(`/metrics`)"
      service: "prometheus@internal"
      entryPoints: ["websecure"]
      {{ letsencrypt_boilerplate }}
