{%raw%}
groups:
  - name: Backup date > 7 days
    rules:
    - alert: No backup data from more that 7 days
      expr: (time() - restic_success) > 604800
      for: 15m
      labels:
        severity: page
        sendto: telegram
      annotations:
        summary: '{{ $labels.url }} have not been backuped since more than 3 days!'
        description: '{{ $labels.url }} of job {{ $labels.job }} has restic_success == {{ $value }}seconds (on env: {{$labels.wp_env}}).'
{%endraw%}
