{% raw %}
groups:
  - name: Zeebe
    rules:

    ###############################################################
    - alert: ZeebeQuorumNoLeader
      expr: |-
        count by (job, partition, partitionGroupName) (
          atomix_role{app_instance="prod"}
          == 3
        )
        != 1
      for: 5m
      labels:
        severity: page
        sendto: telegram
        app: phdassess
      annotations:
        description: |-
          Production Zeebe quorum doesn't currently have exactly one leader (it has {{ $value }}).

          See https://prometheus-phdassess.epfl.ch/graph?g0.expr=atomix_role%7Bapp_instance%3D%22prod%22%7D&g0.tab=0

    ###############################################################
    - alert: ZeebeQuorumAbsentee
      expr: |-
        (
          count by (job, partition, partitionGroupName) (
            atomix_role{app_instance="prod"}
            == 1
          )
          +
          count by (job, partition, partitionGroupName) (
            atomix_role{app_instance="prod"}
            == 3
          )
          -
          count by (job, partition, partitionGroupName) (
            atomix_role{app_instance="prod"}
          )
        )
        != 0
      for: 5m
      labels:
        severity: page
        sendto: telegram
        app: phdassess
      annotations:
        description: |-
          Production Zeebe quorum has absentees.

          All quorum members should participate in the Raft protocol, either as a leader or a follower. This is not the case currently.

{% endraw %}
          See https://prometheus.noc{{ dns_suffix }}.{{ frontend.domain }}/graph?g0.expr=atomix_role%7Bapp_instance%3D%22prod%22%7D&g0.tab=0
{% raw %}

    ###############################################################
    - alert: ZeebeQuorumIncomplete
      expr: |-
        count by (job, partition, partitionGroupName) (
          atomix_role{app_instance="prod"}
        )
        != 3
      for: 1h
      labels:
        severity: page
        sendto: telegram
        app: phdassess
      annotations:
        description: |-
          Production Zeebe quorum is comprised of {{ $value }} members instead of 3.

          See https://prometheus-phdassess.epfl.ch/graph?g0.expr=atomix_role%7Bapp_instance%3D"prod"%7D&g0.tab=0

    ###############################################################
    - alert: ZeebeQuorumConfused
      # Note: for whatever reason, the
      # zeebe_gateway_topology_partition_roles gauge doesn't have a
      # partitionGroupName label. This could be a bug (to be fixed in
      # a future version of Zeebe); we are leaving the by (...,
      # partitionGroupName) agregations as a future-proofing measure.
      expr: |-
        stddev by (job, partition, partitionGroupName) (
          count_values by (broker, job, partition, partitionGroupName) (
            "zeebe_quorum_member",
            zeebe_gateway_topology_partition_roles{app_instance="prod"}
          )
        )
        > 0
      for: 5m
      labels:
        severity: page
        sendto: telegram
        app: phdassess
      annotations:
        description: |-
          Production Zeebe quorum is confused.

          Members of the quorum have different ideas about who is a leader and who is a follower.

          See https://prometheus-phdassess.epfl.ch/graph?g0.expr=zeebe_gateway_topology_partition_roles%7Bapp_instance%3D%22prod%22%7D&g0.tab=0

    ###############################################################
    - alert: ZeebeQuorumUnhealthy
      expr: |-
        zeebe_health{app_instance="prod"}
        < 1.0
      for: 5m
      labels:
        severity: page
        sendto: telegram
        app: phdassess
      annotations:
        description: |-
          Production Zeebe quorum is unhealthy.

          See https://prometheus-phdassess.epfl.ch/graph?g0.expr=zeebe_health%7Bapp_instance%3D%22prod%22%7D&g0.tab=0

    ###############################################################
    - alert: ZeebeQuorumNotMakingProgressOnNFS
      expr: |-
        increase(atomix_partition_raft_commit_index{app_instance="prod",persistence="nfs"}[5m])
        < 100
      for: 60m
      labels:
        severity: page
        sendto: telegram
        app: phdassess
        description: |-
          Production Zeebe quorum is not making progress.

          The Raft commit index is growing too slowly.

          See https://prometheus-phdassess.epfl.ch/graph?g0.expr=atomix_partition_raft_commit_index%7Bapp_instance%3D%22prod%22%7D&g0.tab=0

    ###############################################################
    - alert: ZeebeQuorumNotMakingProgress
      expr: |-
        increase(atomix_partition_raft_commit_index{app_instance="prod",persistence!="nfs"}[5m])
        < 100
      for: 5m
      labels:
        severity: page
        sendto: telegram
        app: phdassess
        description: |-
          Production Zeebe quorum is not making progress.

          The Raft commit index is growing too slowly.

          See https://prometheus-phdassess.epfl.ch/graph?g0.expr=atomix_partition_raft_commit_index%7Bapp_instance%3D%22prod%22%7D&g0.tab=0
{% endraw %}
