{% if prometheus_debug %}
{%raw%}
groups:
  - name: Alert all the time
    rules:
    - alert: Just another alert
      expr: vector(1)
      for: 1m
      labels:
        severity: page
        sendto: telegram
        app: wordpress
      annotations:
        summary: 'Test please ignore'
        description: 'This is an alert that fires all the time.'
{%endraw%}
{% endif %}
